apiVersion: v2
name: argocd-notifier
description: >-
  Aggregates ArgoCD Application notifications into one live-updating Slack
  message per rollout.
type: application
version: 0.1.0
appVersion: 0.6.0-rc.6
