version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.27'
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`.
      # If `custom-order` is `true`, it follows the order of `sections` option.
      # Default: ["standard", "default"]
      sections:
        - standard # Standard section: captures all standard packages.
        - blank
        - dot
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/BROngineer) # Custom section: groups all imports with the specified Prefix.
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - github.com/BROngineer
issues:
  max-issues-per-linter: 10
  max-same-issues: 5
  fix: true
output:
  sort-order:
    - linter
    - severity
    - file
severity:
  # See the dedicated "severity" documentation section.
  default: "@linter"
