{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argocd-notifier.fullname" . }}-leader-election
  namespace: {{ include "argocd-notifier.leaderElectionNamespace" . }}
  labels:
    {{- include "argocd-notifier.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
{{- end }}
