{{- if and .Values.slack.botToken (not .Values.slack.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-notifier.fullname" . }}
  labels:
    {{- include "argocd-notifier.labels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_BOT_TOKEN: {{ .Values.slack.botToken | quote }}
{{- end }}
