{{- if and .Values.slackBackend.enabled .Values.slackBackend.slack.botToken (not .Values.slackBackend.slack.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-notifier.slackBackendFullname" . }}
  labels:
    {{- include "argocd-notifier.slackBackendLabels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_BOT_TOKEN: {{ .Values.slackBackend.slack.botToken | quote }}
{{- end }}
