//go:build go1.22

// Package backendapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package backendapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Field defines model for Field.
type Field struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// Item defines model for Item.
type Item struct {
	AppName        string    `json:"appName"`
	Cluster        string    `json:"cluster"`
	CommitSHA      *string   `json:"commitSHA,omitempty"`
	CommitURL      *string   `json:"commitURL,omitempty"`
	DetailText     *string   `json:"detailText,omitempty"`
	Fields         *[]Field  `json:"fields,omitempty"`
	Images         *[]string `json:"images,omitempty"`
	Link           *string   `json:"link,omitempty"`
	TargetRevision *string   `json:"targetRevision,omitempty"`
	Trigger        string    `json:"trigger"`
	TriggeredBy    *string   `json:"triggeredBy,omitempty"`
}

// Notification defines model for Notification.
type Notification struct {
	Items   []Item `json:"items"`
	Summary string `json:"summary"`
}

// NotifyRequest defines model for NotifyRequest.
type NotifyRequest struct {
	Notification Notification `json:"notification"`
	Recipient    string       `json:"recipient"`

	// Ref Empty means post new; non-empty means try to edit this message.
	Ref string `json:"ref"`
}

// NotifyResult defines model for NotifyResult.
type NotifyResult struct {
	// Ref Identifies the resulting message for a future edit attempt. Backends that can't edit anything should return a fresh value every call; the core does not treat this as an error.
	Ref string `json:"ref"`
}

// ThreadReplyRequest defines model for ThreadReplyRequest.
type ThreadReplyRequest struct {
	Recipient string `json:"recipient"`

	// Ref The message to reply under.
	Ref  string `json:"ref"`
	Text string `json:"text"`
}

// NotifyJSONRequestBody defines body for Notify for application/json ContentType.
type NotifyJSONRequestBody = NotifyRequest

// ThreadReplyJSONRequestBody defines body for ThreadReply for application/json ContentType.
type ThreadReplyJSONRequestBody = ThreadReplyRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// NotifyWithBody Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /notify (the `Notify` operationId).
	NotifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Notify Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /notify (the `Notify` operationId).
	Notify(ctx context.Context, body NotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ThreadReplyWithBody Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /thread-reply (the `ThreadReply` operationId).
	ThreadReplyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ThreadReply Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /thread-reply (the `ThreadReply` operationId).
	ThreadReply(ctx context.Context, body ThreadReplyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// NotifyWithBody Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /notify (the `Notify` operationId).
func (c *Client) NotifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNotifyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Notify Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /notify (the `Notify` operationId).
func (c *Client) Notify(ctx context.Context, body NotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNotifyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ThreadReplyWithBody Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /thread-reply (the `ThreadReply` operationId).
func (c *Client) ThreadReplyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewThreadReplyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ThreadReply Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /thread-reply (the `ThreadReply` operationId).
func (c *Client) ThreadReply(ctx context.Context, body ThreadReplyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewThreadReplyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewNotifyRequest calls the generic Notify builder with application/json body
func NewNotifyRequest(server string, body NotifyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNotifyRequestWithBody(server, "application/json", bodyReader)
}

// NewNotifyRequestWithBody constructs an http.Request for the Notify method, with any body, and a specified content type
func NewNotifyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notify")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewThreadReplyRequest calls the generic ThreadReply builder with application/json body
func NewThreadReplyRequest(server string, body ThreadReplyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewThreadReplyRequestWithBody(server, "application/json", bodyReader)
}

// NewThreadReplyRequestWithBody constructs an http.Request for the ThreadReply method, with any body, and a specified content type
func NewThreadReplyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/thread-reply")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// NotifyWithBodyWithResponse Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /notify (the `Notify` operationId).
	NotifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NotifyResponse, error)

	// NotifyWithResponse Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /notify (the `Notify` operationId).
	NotifyWithResponse(ctx context.Context, body NotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*NotifyResponse, error)

	// ThreadReplyWithBodyWithResponse Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /thread-reply (the `ThreadReply` operationId).
	ThreadReplyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ThreadReplyResponse, error)

	// ThreadReplyWithResponse Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /thread-reply (the `ThreadReply` operationId).
	ThreadReplyWithResponse(ctx context.Context, body ThreadReplyJSONRequestBody, reqEditors ...RequestEditorFn) (*ThreadReplyResponse, error)
}

type NotifyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *NotifyResult
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r NotifyResponse) GetJSON200() *NotifyResult {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r NotifyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r NotifyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NotifyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r NotifyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ThreadReplyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r ThreadReplyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ThreadReplyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ThreadReplyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ThreadReplyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// NotifyWithBodyWithResponse Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /notify (the `Notify` operationId).
func (c *ClientWithResponses) NotifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NotifyResponse, error) {
	rsp, err := c.NotifyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNotifyResponse(rsp)
}

// NotifyWithResponse Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /notify (the `Notify` operationId).
func (c *ClientWithResponses) NotifyWithResponse(ctx context.Context, body NotifyJSONRequestBody, reqEditors ...RequestEditorFn) (*NotifyResponse, error) {
	rsp, err := c.Notify(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNotifyResponse(rsp)
}

// ThreadReplyWithBodyWithResponse Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /thread-reply (the `ThreadReply` operationId).
func (c *ClientWithResponses) ThreadReplyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ThreadReplyResponse, error) {
	rsp, err := c.ThreadReplyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseThreadReplyResponse(rsp)
}

// ThreadReplyWithResponse Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /thread-reply (the `ThreadReply` operationId).
func (c *ClientWithResponses) ThreadReplyWithResponse(ctx context.Context, body ThreadReplyJSONRequestBody, reqEditors ...RequestEditorFn) (*ThreadReplyResponse, error) {
	rsp, err := c.ThreadReply(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseThreadReplyResponse(rsp)
}

// ParseNotifyResponse parses an HTTP response from a NotifyWithResponse call
func ParseNotifyResponse(rsp *http.Response) (*NotifyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NotifyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NotifyResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 400:
		break // No content-type

	case rsp.StatusCode/100 == 5:
		break // No content-type

	}

	return response, nil
}

// ParseThreadReplyResponse parses an HTTP response from a ThreadReplyWithResponse call
func ParseThreadReplyResponse(rsp *http.Response) (*ThreadReplyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ThreadReplyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Notify Deliver a notification. An empty ref means post a new message; a non-empty ref means the backend should try to edit that message in place if it can — the backend decides how to handle it and returns whatever ref represents the result, which the core stores and passes back on the next call for the same session/recipient.
	// (POST /notify)
	Notify(w http.ResponseWriter, r *http.Request)
	// ThreadReply Post a short reply under an existing message. Only called against backends that declared supportsThreadReply: true at registration.
	// (POST /thread-reply)
	ThreadReply(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Notify operation middleware
func (siw *ServerInterfaceWrapper) Notify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Notify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ThreadReply operation middleware
func (siw *ServerInterfaceWrapper) ThreadReply(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ThreadReply(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/notify", wrapper.Notify)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/thread-reply", wrapper.ThreadReply)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFXdahxHE32VYr4PnMBqVomdm/WVRBIicBwjyWAIuaidrt1pq6e7XVUjaRELeYg8YZ4kdPfsn3cki5BA",
	"rjTarj5VderU6YeqCV0MnrxKNXuopGmpw/z5oyVn0kfkEInVUv7Z4Zxc+tBVpGpWibL1y2o9qW7R9TRy",
	"sp5UTJ96y2Sq2a8DwCb8t8kmPMw/UqMJ6EKpO06MMb7FjkZTN64XJR4/C11n9eqnsydO31++GT01pGjd",
	"Nd3r6PEiUZSLs0pd/vg/06KaVf+b7nidDqROC6PrbcfIjKv0v+1wSYc4R7k+v+OsvxkPRF6SXtKtFRv8",
	"eAjb5ZL4qTMy56svz3Izk90EduBjk30b1C5sgzpUdjjhbfPPYjOrZIQY6bsO+RnFbwInQ75HC15d0qee",
	"RI8r9p/181S9B73nUhobLflxaWWgh8qQNGxjwa9+6KKuoCP0AjGIgqe71+CDP6G9E+UVaAAyVkFbK9CR",
	"CC6priZfYGRX0uSwtVLPUwRJ70b4Ge3iwpBP2CSgLQHnu9YvN3XCIjAgLHrtmUobqJo6rOEcmxvyJt1E",
	"hQb9Cx0i/ErbBCJt6J0BJu3ZJxgmaSGbDdAt8QoadO51Tt0EJjCBBHxQUCYcGEMB9EDMgZ/D2jg11y0T",
	"mkuK7nEB/Q0RXLe0ZUoDcMKH3hsaK3VS6bh5PTH5lHW4d9xWumj9IhzXdUV8SwbmK0Bg6oIS7GsI5mV0",
	"E0CFuxY1DQPmKPT+8g1YBaalFSUmA3dWW0BehsacFAziF1LG9ZUQAUY7Tf9NQySP0dYr7NzXNVxvhppm",
	"nOUlBORNDNarlKEPdYDPBWwDyz26byhq4bWUM20JWeeEWsMVJbk0MkVjrF+e4MkAVncmk2/VFS86KH2b",
	"8uzdRXr4iIszV9/Up/VpGtLQRjWrXtan9ctqUkXUNitkmlGynaWVT3+TgDKnF6aaDRtYlXmS6HkwOboJ",
	"XgdhYYxuGMP0oxSrKrb0LNPaynd9KBvlnvIPEoOXIuhvT0//8eTZW3LuQ8V9T87eJsHUicNXJfNhyM/o",
	"FoE7SoaQe8ih3334cBw6oK1ggdaR2XOIbAxSnMHZG0pmA0FbYlBGL2lv8q2eqc6rtX2DNqiAB8tQw5mH",
	"4tlMi31Hx+Tpm/1+Dbjn7rvIfRkPfndo+qgbCLAeosOGwC7SljXo4c/f/ziAMNRYQwJtuEsYLXrjCLKp",
	"boxUdiubymCKTJKGtWfhE7hrbdPueBMNTJJRIoqQ5IwQfA7xdK95/bLfp18EOwIhSdsx3TpSYXSq2U1P",
	"st09vgx7nvsvbcSIqz9rLV4dKy6D5LH/pyX8ruhS2sC6/9zkJ/Leyv7bXcMv3pUnlgzgEq0X3QhteLUN",
	"NQ6TzUsfY2CVPUpnkNhLT0Tx3zLaVNF6/dcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
